### PR TITLE
Replaced all the mentions from now to vercel

### LINKED ISSUE #181: Migrate "now" to "vercel"
So "now" is deprecated and will stop receiving updates on December 31, 2020.

We need to move from "now" to "vercel".

### PR DESCRIPTION
**Pull request by sovattha**
I tried to put myself in the shoes of someone who never heard about `now` and would just start from scratch, meaning I just removed every possible mention of "now".

I replaced thoroughly every mention and paid attention to the context (did not replace "next right now" which obviously could not be changed to "next right vercel").

I could not replace *.now.sh URLs to *.vercel.app (even if it's the default one) because it seems old apps have not been migrated (yet?) by Vercel.

### CODE REVIEW

**Comment by Vadorequest** [comment]
Thank you @sovattha, it looks good.

Is there anything else to be done, you think?

Do I have the permission to update your PR? I don't see anything to change but there might when I'll take a deeper look. (I believe you need to authorize me to update the PR somehow, but I'm really not familiar with that)

**Comment by sovattha** [comment]
I think I have to invite you to be a collaborator of my repository (which is a fork of yours).

You may edit the PR of course.

I left it as draft for now because I did it around dinner and wanted to double check later if I did not miss anything obvious.

Once ready, I'll just remove the draft status and you may pull it!

**Comment by Vadorequest** [comment]
@sovattha I declined your invitation. There is a better way to allow me to edit the PR, see https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork

Another way I'm thinking about if the above isn't doable, is to merge your PR into another branch and keep working on that branch from there. That'd also do the job :)

**Comment by Vadorequest** [comment]
Merged into https://github.com/UnlyEd/next-right-now/tree/update-doc-migrate-now-to-vercel branch and extra work will happen there

**Comment by sovattha** [comment]
Ok great @Vadorequest !

**Pull request merged**
