### PR TITLE
Use deployment URL as a Github deployenvironment

### PR DESCRIPTION
**Pull request by Demmonius**
Hello Captain!
Here is the most insane feature you've ever seen! It creates a Github deployment each time you push on a pull request.
Now that we have that kind of things, we could think about deleting the "comment on pr" because it's just spam.

### CODE REVIEW

**Comment by Vadorequest** [comment]
[GitHub Actions]
Deployment SUCCESS
	 Commit ed077b5b9841727b802292d78f679f60b5547cab successfully deployed to https://nrn-v1-hyb-mst-aptd-gcms-lcz-sty-c1-5ss0tukp7.now.sh
	Deployment aliased as https://nrn-v1-hyb-mst-aptd-gcms-lcz-sty-c1-integrate.now.sh

**Comment by Vadorequest** [comment]
[GitHub Actions]
E2E tests SUCCESS

**Comment by Vadorequest** [comment]
[GitHub Actions]
Deployment SUCCESS
	 Commit a1edd1478009b90e69837c8c03894e7bc75be783 successfully deployed to https://nrn-v1-hyb-mst-aptd-gcms-lcz-sty-c1-5tkoovnbj.now.sh
	Deployment aliased as https://nrn-v1-hyb-mst-aptd-gcms-lcz-sty-c1-integrate.now.sh

**Comment by Vadorequest** [comment]
[GitHub Actions]
Deployment SUCCESS
	 Commit a1edd1478009b90e69837c8c03894e7bc75be783 successfully deployed to https://nrn-v1-hyb-mst-aptd-gcms-lcz-sty-c1-5tkoovnbj.now.sh
	Deployment aliased as https://nrn-v1-hyb-mst-aptd-gcms-lcz-sty-c1-integrate.now.sh

**Comment by Vadorequest** [comment]
[GitHub Actions]
Deployment SUCCESS
	 Commit f31a469c4a6b1579add9560ea23847dae0210480 successfully deployed to https://nrn-v1-hyb-mst-aptd-gcms-lcz-sty-c1-ovie0zsrc.now.sh
	Deployment aliased as https://nrn-v1-hyb-mst-aptd-gcms-lcz-sty-c1-integrate.now.sh

**Comment by Demmonius** [comment]
It looks impossible to do the same for production :(
Or, we will need to hard-code the production URL in a Github Workflow

**Comment by Vadorequest** [comment]
[GitHub Actions]
E2E tests SUCCESS

**Comment by Vadorequest** [comment]
Well, I don't quite understand the purpose of this.

What's a "github deployment"? As far as I can tell, it's only a comment (i.e: `@github-actions github-actions bot deployed to staging 4 hours ago`), is that right?

I don't think it replaces the current "comment", it really doesn't bring the same benefits:
- It doesn't give the deployment url
- It doesn't give the branch deployment url (alias)
- Therefore, we can't know where things got deployed, we just know on which environment
- It doesn't seem to be usable in the production environment (why?)
- Does it warn when deployment fails? (it looks like so, from the config file, but hasn't been tested above)

Overall, this looks more like a drawback (DX-wise).

It could replace our current comment feature if:
- It grants the same, or similar benefits (prints deployment url and branch alias)
- Is usable on all environments
- Handles failures properly

**Pull request closed without merging**
