### PR TITLE
Use cross-env-shell to run commands that are compatible with Windows

### LINKED ISSUE #286: Windows `yarn start` failure
**Describe the bug**
It seems Windows doesn't like the `. ./` used by the `yarn start`, we should make it Windows compatible.

Feedback provided by other people, I haven't tested myself, but something doesn't seem to work properly.

### PR DESCRIPTION
**Pull request by Vadorequest**
Using cross-env to run local commands that might be executed from UNIX or Windows OS.

Didn't change commands executed through GitHub Actions. (couldn't find a compatible way of doing so, cross-env isn't recognized on GHA for some reason)

### CODE REVIEW

**Comment by Vadorequest** [comment]
Build failed but seems unrelated to the PR, seems related to Vercel. Opened a ticket.

**Comment by Vadorequest** [comment]
@Demmonius Do you have any idea how to do that? I've tried using cross-env but it doesn't work on my Windows computer. It's because we're executing a file using `. ./`

**Comment by Demmonius** [comment]
> @Demmonius Do you have any idea how to do that? I've tried using cross-env but it doesn't work on my Windows computer. It's because we're executing a file using `. ./`

Probably because it's working with `bash` or `sh`. Do we want to adapt it for windows? I think this script is *almost* exclusive to GHA.

**Comment by Vadorequest** [comment]
@Demmonius It is executed locally when running yarn start, it's not exclusive to GHA.

**Comment by Vadorequest** [comment]
Closing, no viable solution found. Best workaround is described in https://github.com/UnlyEd/next-right-now/issues/286#issuecomment-811142005

**Pull request closed without merging**
