### PR TITLE
Remove unnecessary `GITHUB_CI_PR_COMMENT` and use default `GITHUB_TOKEN` instead (comment as `github-actions`)

### PR DESCRIPTION
**Pull request by Demmonius**
@Vadorequest A small PR about changing the way we get the token. In fact, I can only see now that we can do it.

### CODE REVIEW

**Comment by Vadorequest** [comment]
[GitHub Actions]
Deployment **SUCCESS**
Commit 7912b32c545c630c404e402e81338655f0160f29 successfully deployed to https://nrn-v2-mst-aptd-at-lcz-sty-c1-po32mkrbc.vercel.app
Deployment aliased as https://nrn-v2-mst-aptd-at-lcz-sty-c1-refactor-gh.vercel.app

**Comment by Vadorequest** [comment]
@Demmonius I don't get why this is possible now. Also, you didn't update the production file.

**Comment by Demmonius** [comment]
> @Demmonius I don't get why this is possible now. Also, you didn't update the production file.

Github provides a token, we don't need to manage it by ourself!

For the production, we never use the token to comment, so I have nowhere to change it :D

**Comment by Vadorequest** [comment]
Alright, documentation should be updated as well then. The README

**Pull request merged**
