### PR TITLE
Add helpful scripts to analyse NRN own dependencies usage

### PR DESCRIPTION
**Pull request by Vadorequest**
The goal is kinda to "locate unnecessary JS code" 

A bit inspired by https://github.com/vercel/next.js/discussions/10655#discussioncomment-553

Issue open at https://github.com/vercel/next.js/discussions/13646

~~Tried https://github.com/pacocoursey/next-unused but doesn't work, see https://github.com/pacocoursey/next-unused/issues/1~~ => Fixed

### CODE REVIEW

**Comment by Vadorequest** [comment]
[GitHub Actions]
Deployment SUCCESS
	 Commit 45e0121439574db8591d26081bc3a8c7360f30c0 successfully deployed to https://nrn-v2-mst-aptd-gcms-lcz-sty-c1-1xycszu0b.now.sh
	Deployment aliased as https://nrn-v2-mst-aptd-gcms-lcz-sty-c1-analyse.now.sh

**Comment by Vadorequest** [comment]
[GitHub Actions]
E2E tests SUCCESS

**Comment by samuelcastro** [comment]
This is super helpful, could you share the results?

**Comment by Vadorequest** [comment]
Unfortunately while it's helpful, it's not working so nicely, with a lot of false-positive results. Needs quite some brain time to understand what it truly means.

What are you interested by?

It doesn't localise unused code, but rather kind of localise files that aren't used. It doesn't really fills the purpose.

**Comment by Vadorequest** [comment]
https://github.com/pacocoursey/next-unused could be useful, I'll give it a try!

**Comment by Vadorequest** [comment]
[GitHub Actions]
Deployment SUCCESS
	 Commit 16da46e95eaa769dd4fc9de99fe982dc1dd1d91c successfully deployed to https://nrn-v2-mst-aptd-gcms-lcz-sty-c1-2zg8ibhxy.now.sh
	Deployment aliased as https://nrn-v2-mst-aptd-gcms-lcz-sty-c1-analyse.now.sh

**Comment by Vadorequest** [comment]
[GitHub Actions]
Deployment SUCCESS
	 Commit 4dce1627d57f1129ce7e3073db4515fd63742997 successfully deployed to https://nrn-v2-mst-aptd-gcms-lcz-sty-c1-4rtsij6nw.now.sh
	Deployment aliased as https://nrn-v2-mst-aptd-gcms-lcz-sty-c1-analyse.now.sh

**Comment by Vadorequest** [comment]
[GitHub Actions]
E2E tests FAILED
  Download artifacts (screenshots + videos) from `checks` section at the top

**Comment by Vadorequest** [comment]
[GitHub Actions]
Deployment SUCCESS
	 Commit 60f4ca55ff03afea6bd4c338b11ab5581844757e successfully deployed to https://nrn-v2-mst-aptd-gcms-lcz-sty-c1-otxhwt0w1.now.sh
	Deployment aliased as https://nrn-v2-mst-aptd-gcms-lcz-sty-c1-analyse.now.sh

**Comment by Vadorequest** [comment]
v0.0.3 fixed the next-unused issue, waiting for a way to remove test files from the output. See https://github.com/pacocoursey/next-unused/issues/1#issuecomment-692088624

**Pull request merged**
