### PR TITLE
Docs massive rewrite

### PR DESCRIPTION
**Pull request by Vadorequest**
Migrate docs from .md to Github Pages and review the whole "getting started" process.

### CODE REVIEW

**Comment by Vadorequest** [comment]
[GitHub Actions]
Deployment SUCCESS
	 Commit 171e11b32ae53d2541ca3fe9df436c6ec481bdff successfully deployed to https://nrn-v1-ssr-customer1-isgll7z0w.now.sh
	Deployment aliased as https://nrn-v1-ssr-customer1-docs-massive-rewrite.now.sh

**Comment by Vadorequest** [comment]
[GitHub Actions]
E2E tests SUCCESS

**Comment by Vadorequest** [comment]
[GitHub Actions]
Deployment SUCCESS
	 Commit 2364e11fa24efa5070ea5c6ce7a8f0476d02f15b successfully deployed to https://nrn-v1-ssr-customer1-lyvazxxxy.now.sh
	Deployment aliased as https://nrn-v1-ssr-customer1-docs-massive-rewrite.now.sh

**Comment by Vadorequest** [comment]
[GitHub Actions]
E2E tests SUCCESS

**Comment by Vadorequest** [comment]
[GitHub Actions]
Deployment SUCCESS
	 Commit a28759292305c7f32e0383d5598aca94e4c25e33 successfully deployed to https://nrn-v1-ssr-customer1-mj1992toi.now.sh
	Deployment aliased as https://nrn-v1-ssr-customer1-docs-massive-rewrite.now.sh

**Comment by Vadorequest** [comment]
[GitHub Actions]
E2E tests SUCCESS

**Comment by Vadorequest** [comment]
[GitHub Actions]
Deployment SUCCESS
	 Commit c68a7e142099c720d63f1e48639c463e8780a14c successfully deployed to https://nrn-v1-ssr-customer1-11u1u8cul.now.sh
	Deployment aliased as https://nrn-v1-ssr-customer1-docs-massive-rewrite.now.sh

**Comment by Vadorequest** [comment]
[GitHub Actions]
E2E tests SUCCESS

**Comment by Vadorequest** [comment]
[GitHub Actions]
Deployment SUCCESS
	 Commit 951314022a634c4d8d931672a2db6f47025882c2 successfully deployed to https://nrn-v1-ssr-customer1-gxh89udah.now.sh
	Deployment aliased as https://nrn-v1-ssr-customer1-docs-massive-rewrite.now.sh

**Comment by Vadorequest** [comment]
[GitHub Actions]
E2E tests SUCCESS

**Comment by Vadorequest** [comment]
[GitHub Actions]
Deployment SUCCESS
	 Commit 23fc9ae48131addaf6f0351f616c6f7fa907e3ea successfully deployed to https://nrn-v1-ssr-customer1-qlzfikw2l.now.sh
	Deployment aliased as https://nrn-v1-ssr-customer1-docs-massive-rewrite.now.sh

**Comment by Vadorequest** [comment]
[GitHub Actions]
E2E tests SUCCESS

**Comment by Vadorequest** [comment]
[GitHub Actions]
Deployment SUCCESS
	 Commit a33796e55209ee96a93568676cf91b51e9d6510a successfully deployed to https://nrn-v1-ssr-customer1-bqz4y5sa6.now.sh
	Deployment aliased as https://nrn-v1-ssr-customer1-docs-massive-rewrite.now.sh

**Comment by Vadorequest** [comment]
[GitHub Actions]
E2E tests SUCCESS

**Comment by Vadorequest** [comment]
[GitHub Actions]
Deployment SUCCESS
	 Commit 198ae6c4e0375f34c99c280782bb6c832290cfa4 successfully deployed to https://nrn-v1-ssr-customer1-g0pvm9t7n.now.sh
	Deployment aliased as https://nrn-v1-ssr-customer1-docs-massive-rewrite.now.sh

**Comment by Vadorequest** [comment]
[GitHub Actions]
E2E tests SUCCESS

**Comment by Vadorequest** [comment]
[GitHub Actions]
Deployment SUCCESS
	 Commit 30cff608a107b5c4ac382909eab08b16904c27b9 successfully deployed to https://nrn-v1-ssr-customer1-fcaamet91.now.sh
	Deployment aliased as https://nrn-v1-ssr-customer1-docs-massive-rewrite.now.sh

**Comment by Vadorequest** [comment]
[GitHub Actions]
E2E tests SUCCESS

**Comment by jajourda** [comment]
I don't understand what you mean by this https://github.com/UnlyEd/next-right-now/pull/22#issue-395080391:

> Migrate docs from .md to Github Pages and review the whole "getting started" process.

How are you planning to migrate from .md?

**Comment by jajourda** [comment]
like this so far. i want to polish it presentation wise
image

**Comment by jajourda** [comment]
I merged your changes with my own docs attempts on my forked repo. I use your master as the upstream to stay up-to-date and i'm toying with jajourda-docs

https://github.com/jajourda/next-right-now/tree/jajourda-docs

**Comment by Vadorequest** [comment]
Okay! I advise you not to work on the docs too much, as I'm still on it with big rewrite, and I believe it's not the right time to attempt to polish it, bc there are too many changes at the moment.

I think it'll be useful to polish once the current version is released, which shouldn't take too long (either today or tomorrow) 😉

**Comment by jajourda** [comment]
@Vadorequest , even if it never becomes a pull-request and/or your changes make my changes obsolete, I am doing it to have my own walkthrough :)

**Comment by jajourda** [comment]
take a look at the default-variant.md file I created as an example of an  **E2E** walkthrough.
https://github.com/jajourda/next-right-now/blob/jajourda-docs/docs/guides/up-and-running/default-variant.md

_It might help to look at it by checking out the `jajourda-docs` branch locally and seeing what it looks like in the context of the just the docs jekyll theme_

**Comment by Vadorequest** [comment]
[GitHub Actions]
Deployment SUCCESS
	 Commit 0c1386b37fd33e24077849f721781dca2fc903b0 successfully deployed to https://nrn-v1-ssr-customer1-fcsu0bi5i.now.sh
	Deployment aliased as https://nrn-v1-ssr-customer1-docs-massive-rewrite.now.sh

**Comment by Vadorequest** [comment]
[GitHub Actions]
E2E tests SUCCESS

**Comment by Vadorequest** [comment]
[GitHub Actions]
Deployment SUCCESS
	 Commit cb4e68866549a22c1ab24d3753d6c9266725cf81 successfully deployed to https://nrn-v1-ssr-customer1-571tk4536.now.sh
	Deployment aliased as https://nrn-v1-ssr-customer1-docs-massive-rewrite.now.sh

**Comment by Vadorequest** [comment]
[GitHub Actions]
E2E tests SUCCESS

**Comment by Vadorequest** [comment]
[GitHub Actions]
Deployment SUCCESS
	 Commit a51d29a7bb3f1c27fe9ff96a984b1dd3e82d6178 successfully deployed to https://nrn-v1-ssr-customer1-aelvs4plb.now.sh
	Deployment aliased as https://nrn-v1-ssr-customer1-docs-massive-rewrite.now.sh

**Comment by Vadorequest** [comment]
[GitHub Actions]
E2E tests SUCCESS

**Comment by Vadorequest** [comment]
@jajourda I've merged. Would you mind taking a close look? I believe it should be much, much easier to understand it all, and follow the getting started guide.

There has been tons of changes, really. So it's likely that I missed a few things!

I won't work on the doc for a little while, I'll rather focus on the implementation of a few presets, so feel free to make a documentation improvement PR! :)

**Pull request merged**
