### PR TITLE
From #53 - Automatically optimizing images. (jpeg, png, svg, webp and gif).

### PR DESCRIPTION
**Pull request by Vadorequest**
Imported from #53

### CODE REVIEW

**Comment by Vadorequest** [comment]
[GitHub Actions]
Deployment SUCCESS
	 Commit 7fce765c80eb1640fe54194b256fabef496e58dc successfully deployed to https://nrn-v1-hyb-mst-aptd-gcms-lcz-sty-c1-7scro7s5a.now.sh
	Deployment aliased as https://nrn-v1-hyb-mst-aptd-gcms-lcz-sty-c1-next-opti.now.sh

**Comment by Vadorequest** [comment]
[GitHub Actions]
E2E tests SUCCESS

**Comment by Vadorequest** [comment]
@samuelcastro Lighthouse doesn't seem to see much improvements, but I don't think it's a significant test, due to the lack of images usage (3-4 images per page isn't significant).

- Before: https://lighthouse-dot-webdotdevsite.appspot.com//lh/html?url=https%3A%2F%2Fnrn-v1-hyb-mst-aptd-gcms-lcz-sty-c1-52i6hio98.now.sh%2Fen%2Fexamples
- Now: https://lighthouse-dot-webdotdevsite.appspot.com//lh/html?url=https%3A%2F%2Fnrn-v1-hyb-mst-aptd-gcms-lcz-sty-c1-7scro7s5a.now.sh%2Fen%2Fexamples

See `Performances > Passed audits > Defer offscreen images`.

**Comment by Vadorequest** [comment]
I tried comparing https://nrn-v1-hyb-mst-aptd-gcms-lcz-sty-c1-52i6hio98.now.sh/fr/examples and https://nrn-v1-hyb-mst-aptd-gcms-lcz-sty-c1-7scro7s5a.now.sh/fr/examples using the network panel, but it's hard to know how effective it is. (images from GraphCMS are already optimised using their API)

I think we need a page with some static images (png/jpg not from GraphCMS) to really see the difference. 🤔

**Comment by Vadorequest** [comment]
[GitHub Actions]
Deployment SUCCESS
	 Commit 6a9bebb836389480ca6707f715e353b82f5602ad successfully deployed to https://nrn-v1-hyb-mst-aptd-gcms-lcz-sty-c1-cok6c82jm.now.sh
	Deployment aliased as https://nrn-v1-hyb-mst-aptd-gcms-lcz-sty-c1-next-opti.now.sh

**Comment by Vadorequest** [comment]
I've added two examples in [https://github.com/UnlyEd/next-right-now/pull/58/commits/6a9bebb836389480ca6707f715e353b82f5602ad ](https://github.com/UnlyEd/next-right-now/pull/58/commits/6a9bebb836389480ca6707f715e353b82f5602ad) and didn't notice any change in localhost (image is still 14.7MB on both examples).

Pushing online on Zeit didn't provide any improvement either, at https://nrn-v1-hyb-mst-aptd-gcms-lcz-sty-c1-cok6c82jm.now.sh/fr/examples.

image

**Comment by Vadorequest** [comment]
[GitHub Actions]
E2E tests SUCCESS

**Comment by samuelcastro** [comment]
We won't see significant improvements since we're not heavily importing images.

**Comment by Vadorequest** [comment]
@samuelcastro That's why I pushed another image example, with a 14.7MB image, but no improvement whatsoever 😢 - See [https://github.com/UnlyEd/next-right-now/pull/58/commits/6a9bebb836389480ca6707f715e353b82f5602ad ](https://github.com/UnlyEd/next-right-now/pull/58/commits/6a9bebb836389480ca6707f715e353b82f5602ad)

**Comment by samuelcastro** [comment]
This is weird.

**Comment by samuelcastro** [comment]
Ok this might be related: https://github.com/cyrilwanner/next-optimized-images/issues/113

**Comment by Vadorequest** [comment]
Thanks for pointing out the issue. 

Until it's fixed, I suggest we don't merge it as it may make believe images are optimised when they aren't.

**Comment by samuelcastro** [comment]
I agree.

**Comment by samuelcastro** [comment]
FYI: The [canary](https://github.com/cyrilwanner/next-optimized-images/releases/tag/v3.0.0-canary.10) release of the new version is out there.

**Comment by Vadorequest** [comment]
Great! I'll wait for a stable release to do any more work on this but I'm following it too, thanks for pointing it out 😉

**Pull request closed without merging**
