### PR TITLE
Including Babel Plugin Graphql Tag to optmize graph-tag usage - from #54

### PR DESCRIPTION
**Pull request by Vadorequest**

### CODE REVIEW

**Comment by Vadorequest** [comment]
[GitHub Actions]
Deployment SUCCESS
	 Commit b38cf24c47609b464949089a6b346d20f30f0f27 successfully deployed to https://nrn-v1-hyb-mst-aptd-gcms-lcz-sty-c1-buaxxg6y0.now.sh
	Deployment aliased as https://nrn-v1-hyb-mst-aptd-gcms-lcz-sty-c1-babel-plu.now.sh

**Comment by Vadorequest** [comment]
[GitHub Actions]
E2E tests SUCCESS

**Comment by Vadorequest** [comment]
@samuelcastro There is no build difference whatsoever between this PR and #42 

From https://vercel.com/unly-oss/nrn-v1-hyb-mst-aptd-gcms-lcz-sty-c1/52i6hio98 (latest build at #42)

image

---

From https://vercel.com/unly-oss/nrn-v1-hyb-mst-aptd-gcms-lcz-sty-c1/buaxxg6y0 (this PR)

image

**Comment by samuelcastro** [comment]
> @samuelcastro There is no build difference whatsoever between this PR and #42
> 
> From https://vercel.com/unly-oss/nrn-v1-hyb-mst-aptd-gcms-lcz-sty-c1/52i6hio98 (latest build at #42)
> 
> image
> 
> From https://vercel.com/unly-oss/nrn-v1-hyb-mst-aptd-gcms-lcz-sty-c1/buaxxg6y0 (this PR)
> 
> image

This is expected, we have 1 or 2 pages importing it, it'll make a significant improvement moving forward.

**Comment by Vadorequest** [comment]
I don't get it, I thought it would reduce the whole build size since it's not supposed to bundle graphql-tag anymore.

**Comment by samuelcastro** [comment]
Sorry, you're right, I'm just getting confused with the other PR, so yes the graphql-tag should not be included in the bundle, let me see what's happening.

**Comment by samuelcastro** [comment]
@Vadorequest indeed I'm facing the same issue, I thought it was related to the [fragment requirement](https://github.com/gajus/babel-plugin-graphql-tag#using-fragments) but even after applying those changes I'm not seeing improvements.

I've opened up an issue to follow up here: https://github.com/gajus/babel-plugin-graphql-tag/issues/40

**Comment by samuelcastro** [comment]
Might be related: https://github.com/gajus/babel-plugin-graphql-tag/issues/25

**Comment by Vadorequest** [comment]
Thanks, that doesn't look likely to be fixed anytime soon. :/
Should we close it?

**Comment by samuelcastro** [comment]
> Thanks, that doesn't look likely to be fixed anytime soon. :/
> Should we close it?

Yeah, that looks like it, let's close this for now.

**Pull request closed without merging**
