### PR TITLE
Using fragments on layout to avoid redundancy and to keep a single source of truth

### PR DESCRIPTION
**Pull request by samuelcastro**

### CODE REVIEW

**Comment by Vadorequest** [comment]
i'll wait for https://github.com/UnlyEd/next-right-now/pull/52 to be merged to avoid conflicts, maybe this has been treated in https://github.com/UnlyEd/next-right-now/pull/52 already.

**Comment by samuelcastro** [comment]
Are you planning on merging it soon?

**Comment by Vadorequest** [comment]
Tonight if I can

**Comment by samuelcastro** [comment]
Why not merge this?

**Comment by Vadorequest** [comment]
It has been closed automatically when I deleted the target branch, my bad. Didn't notice!

**Pull request closed without merging**
