### PR TITLE
Demo v2 - Full rework of the demo examples

### LINKED ISSUE #45: Improve demo (UI/UX) + better examples
## Status

PR in progress at https://github.com/UnlyEd/next-right-now/pull/52

## Context
@jajourda @samuelcastro I'd like to know what you think about the current demo (e.g: https://nrn-v1-hyb-mst-aptd-gcms-lcz-sty-c1-oylx1iihd.now.sh/fr)

I think we should add more example and restructure those examples (UI/UX)

It's mostly visual, but do you have any idea about how to do it better? Would you like to work on it?

**Quick list of stuff we should showcase (IMHO):**
- ✅ Use of getStaticProps (SSG)
  - Done in 3 pages
- ✅ Use of getStaticProps with fallback (?)
- ✅ Use of getStaticProps with revalidate (?)
- ✅ Use of getServerSideProps (SSR)
  - Done at /products
- 🏁  ~~Use of getInitialProps (SSR+CSR), should we? I prefer the new getSP/getSSP way, cleaner~~
- ✅ Use of different locales/lang
  - Done in all pages
- ✅  Use of i18next features
  - Done in the /examples page
- ⚠️  Use of i18nLink (client side navigation with i18n support)
  - Done in all pages, but now shown explicitly in the demo
- ✅ Use of custom 404 
- ⚠️  Use of core hooks
  - Done in multiple files/pages, but now shown explicitly in the demo
- ✅ Use of Apollo HOC
  - Done in many pages, both with SSR/SSG (not done with getInitialProps, should we? 🤔)
- ⚠️ Use of graphQL queries
  - Done in many pages, but now shown explicitly in the demo
- ✅ Use of CSR links
  - Done in many pages
- ✅ Use of analytics (Amplitude)
  - Done in all pages, demo at /examples
- ✅ Use of monitoring (Sentry)
  - Done in all pages, demo at /examples
- ✅ Use of API
  - Demo at / with `/api/status`
- ✅ 500 top-level error (would display native 500 error page I guess)
- ✅ 500 page error (would display page with DefaultErrorLayout)
- ✅ 404 page (no obvious example, but easy to reproduce, unlike 500 errors)

Is there anything important we're missing?

### PR DESCRIPTION
**Pull request by Vadorequest**
Fixes #45 

- All examples will live under `/[locale]/examples/` folder
- Examples will be grouped in 4 categories:
  - Next.s native features (SSG/SSR)
  - NRN preset built-in utilities (I18nLink, hooks, error handling, API, scripts)
  - NRN preset built-in features (I18n, monitoring, graphql, css-in-js, analytics, tests, icons, css animations, UI components library, fonts handling, debug mode) 
  - External tools (NRN Admin for content update)

### CODE REVIEW

**Comment by Vadorequest** [comment]
[GitHub Actions]
Deployment SUCCESS
	 Commit 6f7454cd2159c738d9a9f0eaf66303f64a42d75f successfully deployed to https://nrn-v1-hyb-mst-aptd-gcms-lcz-sty-c1-n4lbbf3sc.now.sh
	Deployment aliased as https://nrn-v1-hyb-mst-aptd-gcms-lcz-sty-c1-examples.now.sh

**Comment by Vadorequest** [comment]
[GitHub Actions]
E2E tests SUCCESS

**Comment by Vadorequest** [comment]
[GitHub Actions]
Deployment SUCCESS
	 Commit b026bc9cbceba2f880af692a300ef02725d1c148 successfully deployed to https://nrn-v1-hyb-mst-aptd-gcms-lcz-sty-c1-3ofnpey3j.now.sh
	Deployment aliased as https://nrn-v1-hyb-mst-aptd-gcms-lcz-sty-c1-examples.now.sh

**Comment by Vadorequest** [comment]
[GitHub Actions]
E2E tests SUCCESS

**Comment by Vadorequest** [comment]
@jajourda @samuelcastro let me know what you think of the new visual :)

**Comment by Vadorequest** [comment]
[GitHub Actions]
Deployment SUCCESS
	 Commit 3cca48daa4ba44923c31a82cd394a360ec1fe4eb successfully deployed to https://nrn-v1-hyb-mst-aptd-gcms-lcz-sty-c1-awco7i3cr.now.sh
	Deployment aliased as https://nrn-v1-hyb-mst-aptd-gcms-lcz-sty-c1-examples.now.sh

**Comment by Vadorequest** [comment]
[GitHub Actions]
E2E tests SUCCESS

**Comment by Vadorequest** [comment]
[GitHub Actions]
Deployment SUCCESS
	 Commit 3feb1c0bc4e2c847ccb173cb62a852e81b18b6a1 successfully deployed to https://nrn-v1-hyb-mst-aptd-gcms-lcz-sty-c1-azrlkwr83.now.sh
	Deployment aliased as https://nrn-v1-hyb-mst-aptd-gcms-lcz-sty-c1-examples.now.sh

**Comment by Vadorequest** [comment]
[GitHub Actions]
E2E tests SUCCESS

**Comment by Vadorequest** [comment]
[GitHub Actions]
Deployment SUCCESS
	 Commit 7842b6b9ef54d4b42838fd1a2697e6a30b395e43 successfully deployed to https://nrn-v1-hyb-mst-aptd-gcms-lcz-sty-c1-re73kyfcm.now.sh
	Deployment aliased as https://nrn-v1-hyb-mst-aptd-gcms-lcz-sty-c1-examples.now.sh

**Comment by Vadorequest** [comment]
[GitHub Actions]
E2E tests SUCCESS

**Comment by Vadorequest** [comment]
[GitHub Actions]
Deployment SUCCESS
	 Commit 10c5e52e085b8253e29135f619298e12ee57fd3e successfully deployed to https://nrn-v1-hyb-mst-aptd-gcms-lcz-sty-c1-hm27ilgoe.now.sh
	Deployment aliased as https://nrn-v1-hyb-mst-aptd-gcms-lcz-sty-c1-examples.now.sh

**Comment by Vadorequest** [comment]
[GitHub Actions]
E2E tests SUCCESS

**Comment by Vadorequest** [comment]
[GitHub Actions]
Deployment SUCCESS
	 Commit 9420c228f706d013fa15999149ae051e0606f10f successfully deployed to https://nrn-v1-hyb-mst-aptd-gcms-lcz-sty-c1-l85pd5aj4.now.sh
	Deployment aliased as https://nrn-v1-hyb-mst-aptd-gcms-lcz-sty-c1-examples.now.sh

**Comment by Vadorequest** [comment]
[GitHub Actions]
E2E tests SUCCESS

**Comment by Vadorequest** [comment]
[GitHub Actions]
Deployment SUCCESS
	 Commit f94b80862e6ca4df02e27573b78794cd1a6de464 successfully deployed to https://nrn-v1-hyb-mst-aptd-gcms-lcz-sty-c1-hwnew33tp.now.sh
	Deployment aliased as https://nrn-v1-hyb-mst-aptd-gcms-lcz-sty-c1-examples.now.sh

**Comment by Vadorequest** [comment]
[GitHub Actions]
E2E tests SUCCESS

**Comment by Vadorequest** [comment]
[GitHub Actions]
Deployment SUCCESS
	 Commit cc03105ad779412c8689ec7618aac8df86c05233 successfully deployed to https://nrn-v1-hyb-mst-aptd-gcms-lcz-sty-c1-7z5mydyig.now.sh
	Deployment aliased as https://nrn-v1-hyb-mst-aptd-gcms-lcz-sty-c1-examples.now.sh

**Comment by Vadorequest** [comment]
[GitHub Actions]
E2E tests SUCCESS

**Comment by Vadorequest** [comment]
[GitHub Actions]
Deployment SUCCESS
	 Commit 2179f36cda80fdb17cea1d96054d887d1703f393 successfully deployed to https://nrn-v1-hyb-mst-aptd-gcms-lcz-sty-c1-h8dye9kyj.now.sh
	Deployment aliased as https://nrn-v1-hyb-mst-aptd-gcms-lcz-sty-c1-examples.now.sh

**Comment by Vadorequest** [comment]
[GitHub Actions]
E2E tests SUCCESS

**Comment by Vadorequest** [comment]
[GitHub Actions]
Deployment SUCCESS
	 Commit e61aa4d4f9519844f2af1eea78a123a9e19f1aa8 successfully deployed to https://nrn-v1-hyb-mst-aptd-gcms-lcz-sty-c1-bz6a6v4e3.now.sh
	Deployment aliased as https://nrn-v1-hyb-mst-aptd-gcms-lcz-sty-c1-examples.now.sh

**Comment by Vadorequest** [comment]
[GitHub Actions]
E2E tests SUCCESS

**Comment by Vadorequest** [comment]
[GitHub Actions]
Deployment SUCCESS
	 Commit 70402c65adce4604a11db335791c6c8ce98a2b0a successfully deployed to https://nrn-v1-hyb-mst-aptd-gcms-lcz-sty-c1-dplzfq8bi.now.sh
	Deployment aliased as https://nrn-v1-hyb-mst-aptd-gcms-lcz-sty-c1-examples.now.sh

**Comment by Vadorequest** [comment]
[GitHub Actions]
E2E tests SUCCESS

**Comment by Vadorequest** [comment]
[GitHub Actions]
Deployment SUCCESS
	 Commit fdafad166b7ee230ed3155a561a12eeaec165b53 successfully deployed to https://nrn-v1-hyb-mst-aptd-gcms-lcz-sty-c1-cg9jbzudn.now.sh
	Deployment aliased as https://nrn-v1-hyb-mst-aptd-gcms-lcz-sty-c1-examples.now.sh

**Comment by Vadorequest** [comment]
[GitHub Actions]
E2E tests SUCCESS

**Comment by Vadorequest** [comment]
[GitHub Actions]
Deployment SUCCESS
	 Commit 67648bf67966e58c8f6c77565716d7bf7d9a46d8 successfully deployed to https://nrn-v1-hyb-mst-aptd-gcms-lcz-sty-c1-5kcvix2hg.now.sh
	Deployment aliased as https://nrn-v1-hyb-mst-aptd-gcms-lcz-sty-c1-examples.now.sh

**Comment by Vadorequest** [comment]
[GitHub Actions]
E2E tests SUCCESS

**Comment by Vadorequest** [comment]
[GitHub Actions]
Deployment SUCCESS
	 Commit 50d6b4a0ac41b37876fc7b62024ec1a793786aa8 successfully deployed to https://nrn-v1-hyb-mst-aptd-gcms-lcz-sty-c1-8xrd0n4h0.now.sh
	Deployment aliased as https://nrn-v1-hyb-mst-aptd-gcms-lcz-sty-c1-examples.now.sh

**Comment by Vadorequest** [comment]
[GitHub Actions]
E2E tests SUCCESS

**Comment by Vadorequest** [comment]
[GitHub Actions]
Deployment SUCCESS
	 Commit 7babe75149d3e1473780bb26eb8f2305c88ca46b successfully deployed to https://nrn-v1-hyb-mst-aptd-gcms-lcz-sty-c1-jcv2b0ndo.now.sh
	Deployment aliased as https://nrn-v1-hyb-mst-aptd-gcms-lcz-sty-c1-examples.now.sh

**Comment by Vadorequest** [comment]
[GitHub Actions]
E2E tests SUCCESS

**Comment by Vadorequest** [comment]
[GitHub Actions]
Deployment SUCCESS
	 Commit 977118f50f0faed416db33ad8d7d501c668e5cdc successfully deployed to https://nrn-v1-hyb-mst-aptd-gcms-lcz-sty-c1-hey5q0pkr.now.sh
	Deployment aliased as https://nrn-v1-hyb-mst-aptd-gcms-lcz-sty-c1-examples.now.sh

**Comment by Vadorequest** [comment]
[GitHub Actions]
Deployment SUCCESS
	 Commit ce929bbeb085b98f3727d7a2936f86ec74e03af1 successfully deployed to https://nrn-v1-hyb-mst-aptd-gcms-lcz-sty-c1-r4xwwwzez.now.sh
	Deployment aliased as https://nrn-v1-hyb-mst-aptd-gcms-lcz-sty-c1-examples.now.sh

**Comment by Vadorequest** [comment]
[GitHub Actions]
E2E tests FAILED
  Download artifacts (screenshots + videos) from `checks` section at the top

**Comment by Vadorequest** [comment]
[GitHub Actions]
Deployment SUCCESS
	 Commit 0f9ad1fae786120c3e1500d824d6ff1c3e7e1ace successfully deployed to https://nrn-v1-hyb-mst-aptd-gcms-lcz-sty-c1-9gvyy8sih.now.sh
	Deployment aliased as https://nrn-v1-hyb-mst-aptd-gcms-lcz-sty-c1-examples.now.sh

**Comment by Vadorequest** [comment]
[GitHub Actions]
E2E tests SUCCESS

**Comment by Vadorequest** [comment]
[GitHub Actions]
Deployment SUCCESS
	 Commit 103f6d4090d28704560a52dcb1f8d253790b4a70 successfully deployed to https://nrn-v1-hyb-mst-aptd-gcms-lcz-sty-c1-9mhzqet87.now.sh
	Deployment aliased as https://nrn-v1-hyb-mst-aptd-gcms-lcz-sty-c1-examples.now.sh

**Comment by Vadorequest** [comment]
[GitHub Actions]
E2E tests SUCCESS

**Comment by Vadorequest** [comment]
[GitHub Actions]
Deployment SUCCESS
	 Commit e8c4bb56562c951221151c9d36c6c28dd31c19cf successfully deployed to https://nrn-v1-hyb-mst-aptd-gcms-lcz-sty-c1-n0p6ih0yd.now.sh
	Deployment aliased as https://nrn-v1-hyb-mst-aptd-gcms-lcz-sty-c1-examples.now.sh

**Comment by Vadorequest** [comment]
[GitHub Actions]
E2E tests SUCCESS

**Comment by Vadorequest** [comment]
[GitHub Actions]
Deployment SUCCESS
	 Commit 9325a8805e9b2b91271d92f7d9615f79061355bf successfully deployed to https://nrn-v1-hyb-mst-aptd-gcms-lcz-sty-c1-au1nmzqqh.now.sh
	Deployment aliased as https://nrn-v1-hyb-mst-aptd-gcms-lcz-sty-c1-examples.now.sh

**Comment by Vadorequest** [comment]
[GitHub Actions]
E2E tests SUCCESS

**Comment by Vadorequest** [comment]
[GitHub Actions]
Deployment SUCCESS
	 Commit 1ba5b92ed888734324c33d4f37cb3156679081bd successfully deployed to https://nrn-v1-hyb-mst-aptd-gcms-lcz-sty-c1-gc9jnmzuk.now.sh
	Deployment aliased as https://nrn-v1-hyb-mst-aptd-gcms-lcz-sty-c1-examples.now.sh

**Comment by Vadorequest** [comment]
[GitHub Actions]
E2E tests SUCCESS

**Comment by Vadorequest** [comment]
[GitHub Actions]
Deployment SUCCESS
	 Commit a56f1b4ca6115ebd83b8fad9fd43b06078f3df6f successfully deployed to https://nrn-v1-hyb-mst-aptd-gcms-lcz-sty-c1-dremhh2fu.now.sh
	Deployment aliased as https://nrn-v1-hyb-mst-aptd-gcms-lcz-sty-c1-examples.now.sh

**Comment by Vadorequest** [comment]
[GitHub Actions]
E2E tests SUCCESS

**Comment by Vadorequest** [comment]
[GitHub Actions]
Deployment SUCCESS
	 Commit b914e6095e0cb4fc08a1d5d5b324441138bb7b76 successfully deployed to https://nrn-v1-hyb-mst-aptd-gcms-lcz-sty-c1-mjnthl8dh.now.sh
	Deployment aliased as https://nrn-v1-hyb-mst-aptd-gcms-lcz-sty-c1-examples.now.sh

**Comment by Vadorequest** [comment]
[GitHub Actions]
E2E tests SUCCESS

**Comment by Vadorequest** [comment]
[GitHub Actions]
Deployment SUCCESS
	 Commit 62c54b159f532e84cc1f831b5a0310518468a8de successfully deployed to https://nrn-v1-hyb-mst-aptd-gcms-lcz-sty-c1-fmk88ford.now.sh
	Deployment aliased as https://nrn-v1-hyb-mst-aptd-gcms-lcz-sty-c1-examples.now.sh

**Comment by Vadorequest** [comment]
[GitHub Actions]
E2E tests SUCCESS

**Comment by Vadorequest** [comment]
[GitHub Actions]
Deployment SUCCESS
	 Commit 52d861a676800d9c18abbec86e902ae240f36ac4 successfully deployed to https://nrn-v1-hyb-mst-aptd-gcms-lcz-sty-c1-77owf9h1k.now.sh
	Deployment aliased as https://nrn-v1-hyb-mst-aptd-gcms-lcz-sty-c1-examples.now.sh

**Comment by Vadorequest** [comment]
[GitHub Actions]
E2E tests SUCCESS

**Comment by Vadorequest** [comment]
[GitHub Actions]
Deployment SUCCESS
	 Commit 797d96b616050638707b285f45fc08b5c34df6c5 successfully deployed to https://nrn-v1-hyb-mst-aptd-gcms-lcz-sty-c1-etuwmo0gy.now.sh
	Deployment aliased as https://nrn-v1-hyb-mst-aptd-gcms-lcz-sty-c1-examples.now.sh

**Comment by Vadorequest** [comment]
[GitHub Actions]
E2E tests SUCCESS

**Comment by Vadorequest** [comment]
[GitHub Actions]
Deployment SUCCESS
	 Commit 94f3e57fa34b9486ed12c1946d4967cd0e2d55c7 successfully deployed to https://nrn-v1-hyb-mst-aptd-gcms-lcz-sty-c1-6e7a9wx1u.now.sh
	Deployment aliased as https://nrn-v1-hyb-mst-aptd-gcms-lcz-sty-c1-examples.now.sh

**Comment by Vadorequest** [comment]
[GitHub Actions]
E2E tests SUCCESS

**Comment by Vadorequest** [comment]
[GitHub Actions]
Deployment FAILED
	 Commit 692a4ba0aa9bef65a5b7b26a111bb589285f1571 failed to deploy to  (click to see logs)

**Comment by Vadorequest** [comment]
[GitHub Actions]
Deployment FAILED
	 Commit d4f0e4ba21884ccfccd79384a0e290dc5c601033 failed to deploy to  (click to see logs)

**Comment by Vadorequest** [comment]
[GitHub Actions]
Deployment FAILED
	 Commit 9846e2e416fa3f863cc2693a0f7f49bbfd957205 failed to deploy to  (click to see logs)

**Comment by Vadorequest** [comment]
[GitHub Actions]
Deployment SUCCESS
	 Commit 6b62fd109ebfe00c6f9c12d9bfd62f40cc3a0265 successfully deployed to https://nrn-v1-hyb-mst-aptd-gcms-lcz-sty-c1-g9wkeoqqv.now.sh
	Deployment aliased as https://nrn-v1-hyb-mst-aptd-gcms-lcz-sty-c1-examples.now.sh

**Comment by samuelcastro** [comment]
> @jajourda @samuelcastro let me know what you think of the new visual :)

It looks way better now, I like how you broke down features into cards. Cleaner and easer to understand now.

**Comment by Vadorequest** [comment]
Thanks! It's almost done. There is only a few examples about SSG/R missing. That was more work than intended 😓

**Comment by Vadorequest** [comment]
[GitHub Actions]
Deployment SUCCESS
	 Commit 582d633033ad5746b997d98d925eec812026fa69 successfully deployed to https://nrn-v1-hyb-mst-aptd-gcms-lcz-sty-c1-513utv1z1.now.sh
	Deployment aliased as https://nrn-v1-hyb-mst-aptd-gcms-lcz-sty-c1-examples.now.sh

**Comment by Vadorequest** [comment]
[GitHub Actions]
Deployment SUCCESS
	 Commit 53b0f853cd317eef7012fe0966f2ceb24a9197fc successfully deployed to https://nrn-v1-hyb-mst-aptd-gcms-lcz-sty-c1-g99eujlm6.now.sh
	Deployment aliased as https://nrn-v1-hyb-mst-aptd-gcms-lcz-sty-c1-examples.now.sh

**Comment by Vadorequest** [comment]
Added https://github.com/welldone-software/why-did-you-render, very interesting.

**Comment by Vadorequest** [comment]
[GitHub Actions]
Deployment SUCCESS
	 Commit b54f416c6626a8de7bba0087e6203d55286be9d8 successfully deployed to https://nrn-v1-hyb-mst-aptd-gcms-lcz-sty-c1-7ixoxlim5.now.sh
	Deployment aliased as https://nrn-v1-hyb-mst-aptd-gcms-lcz-sty-c1-examples.now.sh

**Comment by Vadorequest** [comment]
[GitHub Actions]
Deployment SUCCESS
	 Commit 80182c076ae2b399213741006f571edc6270eb8f successfully deployed to https://nrn-v1-hyb-mst-aptd-gcms-lcz-sty-c1-ccw3rn1qn.now.sh
	Deployment aliased as https://nrn-v1-hyb-mst-aptd-gcms-lcz-sty-c1-examples.now.sh

**Comment by Vadorequest** [comment]
[GitHub Actions]
Deployment SUCCESS
	 Commit c08feb87b3bff65982f7448a7cc7b4a8b8c0fa7b successfully deployed to https://nrn-v1-hyb-mst-aptd-gcms-lcz-sty-c1-3x3dmfxms.now.sh
	Deployment aliased as https://nrn-v1-hyb-mst-aptd-gcms-lcz-sty-c1-examples.now.sh

**Comment by Vadorequest** [comment]
[GitHub Actions]
Deployment SUCCESS
	 Commit 03b1c186cfe44437851415ebca5ad38da7c819a4 successfully deployed to https://nrn-v1-hyb-mst-aptd-gcms-lcz-sty-c1-wkc81ndqq.now.sh
	Deployment aliased as https://nrn-v1-hyb-mst-aptd-gcms-lcz-sty-c1-examples.now.sh

**Comment by Vadorequest** [comment]
[GitHub Actions]
E2E tests FAILED
  Download artifacts (screenshots + videos) from `checks` section at the top

**Comment by Vadorequest** [comment]
[GitHub Actions]
Deployment SUCCESS
	 Commit 4cc03c42a9c325b94b6899a6fc567870579a40cb successfully deployed to https://nrn-v1-hyb-mst-aptd-gcms-lcz-sty-c1-kfog6p1gk.now.sh
	Deployment aliased as https://nrn-v1-hyb-mst-aptd-gcms-lcz-sty-c1-examples.now.sh

**Comment by Vadorequest** [comment]
[GitHub Actions]
E2E tests FAILED
  Download artifacts (screenshots + videos) from `checks` section at the top

**Comment by Vadorequest** [comment]
[GitHub Actions]
Deployment SUCCESS
	 Commit fd95ce9195cd810d535592625f9bebfd4b158995 successfully deployed to https://nrn-v1-hyb-mst-aptd-gcms-lcz-sty-c1-fugz1ho97.now.sh
	Deployment aliased as https://nrn-v1-hyb-mst-aptd-gcms-lcz-sty-c1-examples.now.sh

**Comment by Vadorequest** [comment]
[GitHub Actions]
Deployment SUCCESS
	 Commit d5e23bd7cd5d848f8a62e074cb8769fbfc67a6a4 successfully deployed to https://nrn-v1-hyb-mst-aptd-gcms-lcz-sty-c1-kt8ilrb49.now.sh
	Deployment aliased as https://nrn-v1-hyb-mst-aptd-gcms-lcz-sty-c1-examples.now.sh

**Comment by Vadorequest** [comment]
[GitHub Actions]
Deployment SUCCESS
	 Commit 8176ad30c6a08f8132a8da9630032a333ac65e3c successfully deployed to https://nrn-v1-hyb-mst-aptd-gcms-lcz-sty-c1-q34rk8rj0.now.sh
	Deployment aliased as https://nrn-v1-hyb-mst-aptd-gcms-lcz-sty-c1-examples.now.sh

**Comment by Vadorequest** [comment]
[GitHub Actions]
Deployment SUCCESS
	 Commit 5f8bf63f5e47df341da8000da126d506b36f5b19 successfully deployed to https://nrn-v1-hyb-mst-aptd-gcms-lcz-sty-c1-589kiccp9.now.sh
	Deployment aliased as https://nrn-v1-hyb-mst-aptd-gcms-lcz-sty-c1-examples.now.sh

**Comment by Vadorequest** [comment]
[GitHub Actions]
Deployment SUCCESS
	 Commit 4ba9bb8bc86078581649ae4dd30a3591048c0547 successfully deployed to https://nrn-v1-hyb-mst-aptd-gcms-lcz-sty-c1-jqgd0c1iv.now.sh
	Deployment aliased as https://nrn-v1-hyb-mst-aptd-gcms-lcz-sty-c1-examples.now.sh

**Comment by Vadorequest** [comment]
[GitHub Actions]
Deployment SUCCESS
	 Commit d5a27ec51c26bae662a946550cec4748d3e7b3ba successfully deployed to https://nrn-v1-hyb-mst-aptd-gcms-lcz-sty-c1-80xc6je1b.now.sh
	Deployment aliased as https://nrn-v1-hyb-mst-aptd-gcms-lcz-sty-c1-examples.now.sh

**Comment by Vadorequest** [comment]
[GitHub Actions]
Deployment SUCCESS
	 Commit 34fe273400f8d8792dbfa2cd4eb632c5dd9cdca6 successfully deployed to https://nrn-v1-hyb-mst-aptd-gcms-lcz-sty-c1-dra38qr1c.now.sh
	Deployment aliased as https://nrn-v1-hyb-mst-aptd-gcms-lcz-sty-c1-examples.now.sh

**Comment by Vadorequest** [comment]
[GitHub Actions]
Deployment SUCCESS
	 Commit 08a2209fd8ce6cefcc2e733a321d70a1b8bb586c successfully deployed to https://nrn-v1-hyb-mst-aptd-gcms-lcz-sty-c1-8zo69v8h2.now.sh
	Deployment aliased as https://nrn-v1-hyb-mst-aptd-gcms-lcz-sty-c1-examples.now.sh

**Comment by Vadorequest** [comment]
[GitHub Actions]
Deployment SUCCESS
	 Commit d20d464cb0eb70aace12372ad37bf2acfedf05ca successfully deployed to https://nrn-v1-hyb-mst-aptd-gcms-lcz-sty-c1-l3pqbc8ul.now.sh
	Deployment aliased as https://nrn-v1-hyb-mst-aptd-gcms-lcz-sty-c1-examples.now.sh

**Comment by Vadorequest** [comment]
[GitHub Actions]
Deployment SUCCESS
	 Commit ac88497f5aebad49a5d46de66a94e516adf1656d successfully deployed to https://nrn-v1-hyb-mst-aptd-gcms-lcz-sty-c1-nfz751y6q.now.sh
	Deployment aliased as https://nrn-v1-hyb-mst-aptd-gcms-lcz-sty-c1-examples.now.sh

**Comment by Vadorequest** [comment]
[GitHub Actions]
Deployment SUCCESS
	 Commit 783bd44f798b881d572754386a12f83fdff8c8d8 successfully deployed to https://nrn-v1-hyb-mst-aptd-gcms-lcz-sty-c1-i57udz5fi.now.sh
	Deployment aliased as https://nrn-v1-hyb-mst-aptd-gcms-lcz-sty-c1-examples.now.sh

**Comment by Vadorequest** [comment]
[GitHub Actions]
Deployment SUCCESS
	 Commit e878befe800a15a08ab0128a1ea815c4d8ce84e7 successfully deployed to https://nrn-v1-hyb-mst-aptd-gcms-lcz-sty-c1-i6tj62ina.now.sh
	Deployment aliased as https://nrn-v1-hyb-mst-aptd-gcms-lcz-sty-c1-examples.now.sh

**Pull request merged**
