### PR TITLE
Workflow - Debug Github Actions in local development

### PR DESCRIPTION
**Pull request by Demmonius**
Using **ACT** https://github.com/nektos/act

### CODE REVIEW

**Comment by Demmonius** [comment]
[GitHub Actions]
Deployment **SUCCESS**
Commit 64adfdd0ac2d067b12e0eccd0736d73571003b65 successfully deployed to https://nrn-v2-mst-aptd-at-lcz-sty-c1-ijl9fumu5.vercel.app
Deployment aliased as https://nrn-v2-mst-aptd-at-lcz-sty-c1-gha-test-lo.vercel.app

**Comment by Demmonius** [comment]
[GitHub Actions] - **Lighthouse report** for https://nrn-v2-mst-aptd-at-lcz-sty-c1-7row5bjzt.vercel.app

**Comment by Demmonius** [comment]
[GitHub Actions] - **Lighthouse report** for https://nrn-v2-mst-aptd-at-lcz-sty-c1-7row5bjzt.vercel.app

**Comment by Demmonius** [comment]
[GitHub Actions] - **Lighthouse report** for https://nrn-v2-mst-aptd-at-lcz-sty-c1-7row5bjzt.vercel.app

**Comment by Demmonius** [comment]
I get an error when I use `fromJson`, that's why the comment is broken.
I opened an issue here: https://github.com/nektos/act/issues/281

It looks like **act** doesn't manage basic functions of GHA.

**Comment by Demmonius** [comment]
[GitHub Actions] - **Lighthouse report** for https://nrn-v2-mst-aptd-at-lcz-sty-c1-7row5bjzt.vercel.app

**Comment by Vadorequest** [comment]
Task has been abandoned, we couldn't find a viable solution.

**Pull request closed without merging**
